"""Icon loading with theme → QRC → file-system → Qt-standard fallback chain."""

from __future__ import annotations

import logging
from pathlib import Path

from PyQt5.QtCore import QFile
from PyQt5.QtGui import QIcon
from PyQt5.QtWidgets import QApplication, QStyle

logger = logging.getLogger(__name__)

# Root of the resources directory relative to this file:
#   src/pbprompt/gui/icons.py → ../../../../resources/icons/
_ICON_DIR = Path(__file__).parent.parent.parent.parent / "resources" / "icons"

# Mapping from logical icon name to FreeDesktop theme icon name.
# Used as the first lookup so desktop icon themes are honoured on Linux.
_THEME_ICON_MAP: dict[str, str] = {
    "new": "document-new",
    "open": "document-open",
    "save": "document-save",
    "save_as": "document-save-as",
    "close": "window-close",
    "quit": "application-exit",
    "delete": "edit-delete",
    "options": "preferences-system",
    "about": "help-about",
    "translate_right": "go-next",
    "translate_left": "go-previous",
    "new_prompt": "list-add",
    "duplicate": "edit-copy",
    "import_yaml": "document-import",
    "export_yaml": "document-export",
    "app": "pbprompt",
}

# Mapping from logical icon name to a Qt standard pixmap as last-resort fallback
_STANDARD_ICON_MAP: dict[str, QStyle.StandardPixmap] = {
    "app": QStyle.SP_ComputerIcon,
    "new": QStyle.SP_FileIcon,
    "open": QStyle.SP_DialogOpenButton,
    "save": QStyle.SP_DialogSaveButton,
    "save_as": QStyle.SP_DialogSaveButton,
    "close": QStyle.SP_DialogCloseButton,
    "quit": QStyle.SP_TitleBarCloseButton,
    "delete": QStyle.SP_TrashIcon,
    "options": QStyle.SP_FileDialogDetailedView,
    "about": QStyle.SP_MessageBoxInformation,
    "translate_right": QStyle.SP_ArrowRight,
    "translate_left": QStyle.SP_ArrowLeft,
    "new_prompt": QStyle.SP_FileIcon,
    "duplicate": QStyle.SP_FileDialogContentsView,
    "import_yaml": QStyle.SP_DialogOpenButton,
    "export_yaml": QStyle.SP_DialogSaveButton,
}

# Try to import compiled QRC resources (generated by ``make resources``)
try:
    from pbprompt.gui import resources_rc as _rc  # noqa: F401

    _QRC_AVAILABLE = True
    logger.debug("QRC resources loaded.")
except ImportError:
    _QRC_AVAILABLE = False
    logger.debug("QRC resources not compiled; falling back to file-system icons.")


def get_icon(name: str) -> QIcon:
    """Return a QIcon for *name*, trying theme → QRC → file-system → Qt standard.

    Parameters
    ----------
    name:
        Logical icon name (e.g. ``"new"``, ``"save"``, ``"app"``).

    Returns
    -------
    QIcon
        Loaded icon, or an empty QIcon if nothing found.
    """
    # 1. Desktop icon theme (FreeDesktop, honoured on Linux/KDE/GNOME)
    theme_name = _THEME_ICON_MAP.get(name)
    if theme_name:
        theme_icon = QIcon.fromTheme(theme_name)
        if not theme_icon.isNull():
            return theme_icon

    # 2. Qt resource file – check existence first to avoid spurious Qt warnings
    if _QRC_AVAILABLE:
        qrc_path = f":/icons/{name}.svg"
        if QFile.exists(qrc_path):
            qrc_icon = QIcon(qrc_path)
            if not qrc_icon.isNull():
                return qrc_icon

    # 3. File system (light variant, plain, colour variant)
    for suffix in (".svg", ".png"):
        for variant in (f"{name}_light", name, f"{name}_color"):
            path = _ICON_DIR / f"{variant}{suffix}"
            if path.exists():
                icon = QIcon(str(path))
                if not icon.isNull():
                    return icon

    # 4. Qt built-in fallback
    if name in _STANDARD_ICON_MAP:
        app = QApplication.instance()
        if app:
            return app.style().standardIcon(_STANDARD_ICON_MAP[name])

    logger.debug("No icon found for %r; returning empty QIcon.", name)
    return QIcon()
